### ISSUE TITLE
It would be nice to have Raspberry PI targetted binaries

### ISSUE THREAD

**Issue by BillKress** [kobo/groovyserv#70]
It would be nice to be able to use groovyserv on the raspberry pi without building both GO and groovyserv.

Without goovyserv groovy runs on the RPI so slowly that it is next to useless.  It would be nice to make groovy available to RPI users but a good portion of PI users tend to be young children or new programmers.  If it were just a simple install (or even an apt-get) I think it could help bring groovy to quite a few more people.

**Comment by nobeans** [comment]
It's difficult to provide a appropriate binary for all Raspberry PI series, because the ARM's version is different like this:

* Raspberry Pi 1 (ARMv6 -> `GORARM=6`)
* Raspberry Pi 2 (ARMv7 -> `GORARM=7`)
* Raspberry Pi 3 (ARMv8 -> `GORARM=8`)

`GOOS=linux` and `GOARCH=arm` for golang parameter are common for all, but the right value of `GOARM` is different for each.

(See http://elinux.org/RPi_Hardware and https://github.com/golang/go/wiki/GoArm)
